### ISSUE TITLE
Apostrophe normalisation

### ISSUE THREAD

**Issue by TheGoblinHero** [KerfuffleV2/dhelper#2]
I have "Jarrall's Frostkin" in my decklist, but tier lists include it as "Jarrall’s Frostkin". So dhelper can't rank this card. I think it will be better to normalize apostrophes on deck/tierlist import.

**Comment by KerfuffleV2** [comment]
Thanks for the catch! I've fixed this in 79d43f067f41fa031a6d9f52fbccda6ea5f88d71 in a pretty naive way, but as far as I can see that was the only character causing an issue.
