### ISSUE TITLE
FR - Export deck to Eternal

### ISSUE THREAD

**Issue by TheGoblinHero** [KerfuffleV2/dhelper#3]
Right now I'm building my sealed deck with the help of your great tool.
1. I've chosen the colors (with the help of quarry mode).
2. I've filtered the worthy cards of the chosen colors (i.e. d -f r1.6:c.tpj)
3. Now I need to make the deck. So I want an ability to export the filtered cards in the deck mode to the Eternal format. This way I can import worthy cards inside the game client and think about the final deck composition there.

**Comment by KerfuffleV2** [comment]
> 3. Now I need to make the deck. So I want an ability to export the filtered cards in the deck mode to the Eternal format. This way I can import worthy cards inside the game client and think about the final deck composition there.

@TheGoblinHero 

Thanks for the kind words.

I believe it can already do what you want with the `-w` commandline argument to quarry mode. That will make it write out a deck file for each matching color. The decks will be named `<inputfile>.<COLOR>.lst`.

Please let me know if I've misunderstood.

**Comment by TheGoblinHero** [comment]
I'm not sure if it's needed in the quarry mode. I'd like to have this feature in the deck mode.

**Comment by KerfuffleV2** [comment]
@TheGoblinHero 

That wasn't a use case I'd anticipated but not hard to add. Let me know if you have any issues! You can now use `-w FILE` in deck mode to write out the displayed deck.

**Comment by TheGoblinHero** [comment]
Thx! Exactly what I  wanted.
